// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/denisbytes/javafootball/score_calculator/proto/types.proto

// Protobuf Java Version: 3.25.2
package com.github.denisbytes.javafootball.score_calculator.proto;

public final class MatchServiceProto {
  private MatchServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetMatchesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetMatchesRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetMatchesRequest}
   */
  public static final class GetMatchesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetMatchesRequest)
      GetMatchesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetMatchesRequest.newBuilder() to construct.
    private GetMatchesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetMatchesRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetMatchesRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest)) {
        return super.equals(obj);
      }
      com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest other = (com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetMatchesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetMatchesRequest)
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.Builder.class);
      }

      // Construct using com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesRequest_descriptor;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest getDefaultInstanceForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest build() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest buildPartial() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest result = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest) {
          return mergeFrom((com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest other) {
        if (other == com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetMatchesRequest)
    }

    // @@protoc_insertion_point(class_scope:GetMatchesRequest)
    private static final com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest();
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetMatchesRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetMatchesRequest>() {
      @java.lang.Override
      public GetMatchesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetMatchesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetMatchesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetMatchesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetMatchesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Match matches = 1;</code>
     */
    java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> 
        getMatchesList();
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getMatches(int index);
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    int getMatchesCount();
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    java.util.List<? extends com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder> 
        getMatchesOrBuilderList();
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder getMatchesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetMatchesResponse}
   */
  public static final class GetMatchesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetMatchesResponse)
      GetMatchesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetMatchesResponse.newBuilder() to construct.
    private GetMatchesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetMatchesResponse() {
      matches_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetMatchesResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.Builder.class);
    }

    public static final int MATCHES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> matches_;
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> getMatchesList() {
      return matches_;
    }
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    @java.lang.Override
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    @java.lang.Override
    public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated .Match matches = 1;</code>
     */
    @java.lang.Override
    public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(1, matches_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, matches_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse)) {
        return super.equals(obj);
      }
      com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse other = (com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse) obj;

      if (!getMatchesList()
          .equals(other.getMatchesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMatchesCount() > 0) {
        hash = (37 * hash) + MATCHES_FIELD_NUMBER;
        hash = (53 * hash) + getMatchesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetMatchesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetMatchesResponse)
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.Builder.class);
      }

      // Construct using com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
        } else {
          matches_ = null;
          matchesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_GetMatchesResponse_descriptor;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse getDefaultInstanceForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse build() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse buildPartial() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse result = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse result) {
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
      }

      private void buildPartial0(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse) {
          return mergeFrom((com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse other) {
        if (other == com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse.getDefaultInstance()) return this;
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000001);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match m =
                    input.readMessage(
                        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.parser(),
                        extensionRegistry);
                if (matchesBuilder_ == null) {
                  ensureMatchesIsMutable();
                  matches_.add(m);
                } else {
                  matchesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          matches_ = new java.util.ArrayList<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match>(matches_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder> matchesBuilder_;

      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder setMatches(
          int index, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder setMatches(
          int index, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder addMatches(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder addMatches(
          int index, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder addMatches(
          com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder addMatches(
          int index, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder addAllMatches(
          java.lang.Iterable<? extends com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public java.util.List<? extends com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .Match matches = 1;</code>
       */
      public java.util.List<com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetMatchesResponse)
    }

    // @@protoc_insertion_point(class_scope:GetMatchesResponse)
    private static final com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse();
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetMatchesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetMatchesResponse>() {
      @java.lang.Override
      public GetMatchesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetMatchesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetMatchesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.GetMatchesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Match)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string matchID = 1;</code>
     * @return The matchID.
     */
    java.lang.String getMatchID();
    /**
     * <code>string matchID = 1;</code>
     * @return The bytes for matchID.
     */
    com.google.protobuf.ByteString
        getMatchIDBytes();

    /**
     * <code>string team1 = 2;</code>
     * @return The team1.
     */
    java.lang.String getTeam1();
    /**
     * <code>string team1 = 2;</code>
     * @return The bytes for team1.
     */
    com.google.protobuf.ByteString
        getTeam1Bytes();

    /**
     * <code>string team2 = 3;</code>
     * @return The team2.
     */
    java.lang.String getTeam2();
    /**
     * <code>string team2 = 3;</code>
     * @return The bytes for team2.
     */
    com.google.protobuf.ByteString
        getTeam2Bytes();

    /**
     * <code>repeated string comments = 4;</code>
     * @return A list containing the comments.
     */
    java.util.List<java.lang.String>
        getCommentsList();
    /**
     * <code>repeated string comments = 4;</code>
     * @return The count of comments.
     */
    int getCommentsCount();
    /**
     * <code>repeated string comments = 4;</code>
     * @param index The index of the element to return.
     * @return The comments at the given index.
     */
    java.lang.String getComments(int index);
    /**
     * <code>repeated string comments = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the comments at the given index.
     */
    com.google.protobuf.ByteString
        getCommentsBytes(int index);

    /**
     * <code>int32 team1Goals = 5;</code>
     * @return The team1Goals.
     */
    int getTeam1Goals();

    /**
     * <code>int32 team2Goals = 6;</code>
     * @return The team2Goals.
     */
    int getTeam2Goals();
  }
  /**
   * Protobuf type {@code Match}
   */
  public static final class Match extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Match)
      MatchOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Match.newBuilder() to construct.
    private Match(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Match() {
      matchID_ = "";
      team1_ = "";
      team2_ = "";
      comments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Match();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_Match_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_Match_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder.class);
    }

    public static final int MATCHID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object matchID_ = "";
    /**
     * <code>string matchID = 1;</code>
     * @return The matchID.
     */
    @java.lang.Override
    public java.lang.String getMatchID() {
      java.lang.Object ref = matchID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchID_ = s;
        return s;
      }
    }
    /**
     * <code>string matchID = 1;</code>
     * @return The bytes for matchID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMatchIDBytes() {
      java.lang.Object ref = matchID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEAM1_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object team1_ = "";
    /**
     * <code>string team1 = 2;</code>
     * @return The team1.
     */
    @java.lang.Override
    public java.lang.String getTeam1() {
      java.lang.Object ref = team1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        team1_ = s;
        return s;
      }
    }
    /**
     * <code>string team1 = 2;</code>
     * @return The bytes for team1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeam1Bytes() {
      java.lang.Object ref = team1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        team1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEAM2_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object team2_ = "";
    /**
     * <code>string team2 = 3;</code>
     * @return The team2.
     */
    @java.lang.Override
    public java.lang.String getTeam2() {
      java.lang.Object ref = team2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        team2_ = s;
        return s;
      }
    }
    /**
     * <code>string team2 = 3;</code>
     * @return The bytes for team2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeam2Bytes() {
      java.lang.Object ref = team2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        team2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList comments_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string comments = 4;</code>
     * @return A list containing the comments.
     */
    public com.google.protobuf.ProtocolStringList
        getCommentsList() {
      return comments_;
    }
    /**
     * <code>repeated string comments = 4;</code>
     * @return The count of comments.
     */
    public int getCommentsCount() {
      return comments_.size();
    }
    /**
     * <code>repeated string comments = 4;</code>
     * @param index The index of the element to return.
     * @return The comments at the given index.
     */
    public java.lang.String getComments(int index) {
      return comments_.get(index);
    }
    /**
     * <code>repeated string comments = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the comments at the given index.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes(int index) {
      return comments_.getByteString(index);
    }

    public static final int TEAM1GOALS_FIELD_NUMBER = 5;
    private int team1Goals_ = 0;
    /**
     * <code>int32 team1Goals = 5;</code>
     * @return The team1Goals.
     */
    @java.lang.Override
    public int getTeam1Goals() {
      return team1Goals_;
    }

    public static final int TEAM2GOALS_FIELD_NUMBER = 6;
    private int team2Goals_ = 0;
    /**
     * <code>int32 team2Goals = 6;</code>
     * @return The team2Goals.
     */
    @java.lang.Override
    public int getTeam2Goals() {
      return team2Goals_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(matchID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, matchID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(team1_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, team1_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(team2_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, team2_);
      }
      for (int i = 0; i < comments_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, comments_.getRaw(i));
      }
      if (team1Goals_ != 0) {
        output.writeInt32(5, team1Goals_);
      }
      if (team2Goals_ != 0) {
        output.writeInt32(6, team2Goals_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(matchID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, matchID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(team1_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, team1_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(team2_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, team2_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < comments_.size(); i++) {
          dataSize += computeStringSizeNoTag(comments_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCommentsList().size();
      }
      if (team1Goals_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, team1Goals_);
      }
      if (team2Goals_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, team2Goals_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match)) {
        return super.equals(obj);
      }
      com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match other = (com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match) obj;

      if (!getMatchID()
          .equals(other.getMatchID())) return false;
      if (!getTeam1()
          .equals(other.getTeam1())) return false;
      if (!getTeam2()
          .equals(other.getTeam2())) return false;
      if (!getCommentsList()
          .equals(other.getCommentsList())) return false;
      if (getTeam1Goals()
          != other.getTeam1Goals()) return false;
      if (getTeam2Goals()
          != other.getTeam2Goals()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MATCHID_FIELD_NUMBER;
      hash = (53 * hash) + getMatchID().hashCode();
      hash = (37 * hash) + TEAM1_FIELD_NUMBER;
      hash = (53 * hash) + getTeam1().hashCode();
      hash = (37 * hash) + TEAM2_FIELD_NUMBER;
      hash = (53 * hash) + getTeam2().hashCode();
      if (getCommentsCount() > 0) {
        hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getCommentsList().hashCode();
      }
      hash = (37 * hash) + TEAM1GOALS_FIELD_NUMBER;
      hash = (53 * hash) + getTeam1Goals();
      hash = (37 * hash) + TEAM2GOALS_FIELD_NUMBER;
      hash = (53 * hash) + getTeam2Goals();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Match}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Match)
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.MatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_Match_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_Match_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.class, com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.Builder.class);
      }

      // Construct using com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        matchID_ = "";
        team1_ = "";
        team2_ = "";
        comments_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        team1Goals_ = 0;
        team2Goals_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.internal_static_Match_descriptor;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getDefaultInstanceForType() {
        return com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match build() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match buildPartial() {
        com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match result = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.matchID_ = matchID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.team1_ = team1_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.team2_ = team2_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          comments_.makeImmutable();
          result.comments_ = comments_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.team1Goals_ = team1Goals_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.team2Goals_ = team2Goals_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match) {
          return mergeFrom((com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match other) {
        if (other == com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match.getDefaultInstance()) return this;
        if (!other.getMatchID().isEmpty()) {
          matchID_ = other.matchID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTeam1().isEmpty()) {
          team1_ = other.team1_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTeam2().isEmpty()) {
          team2_ = other.team2_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.comments_.isEmpty()) {
          if (comments_.isEmpty()) {
            comments_ = other.comments_;
            bitField0_ |= 0x00000008;
          } else {
            ensureCommentsIsMutable();
            comments_.addAll(other.comments_);
          }
          onChanged();
        }
        if (other.getTeam1Goals() != 0) {
          setTeam1Goals(other.getTeam1Goals());
        }
        if (other.getTeam2Goals() != 0) {
          setTeam2Goals(other.getTeam2Goals());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                matchID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                team1_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                team2_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCommentsIsMutable();
                comments_.add(s);
                break;
              } // case 34
              case 40: {
                team1Goals_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                team2Goals_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object matchID_ = "";
      /**
       * <code>string matchID = 1;</code>
       * @return The matchID.
       */
      public java.lang.String getMatchID() {
        java.lang.Object ref = matchID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchID = 1;</code>
       * @return The bytes for matchID.
       */
      public com.google.protobuf.ByteString
          getMatchIDBytes() {
        java.lang.Object ref = matchID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchID = 1;</code>
       * @param value The matchID to set.
       * @return This builder for chaining.
       */
      public Builder setMatchID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        matchID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string matchID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatchID() {
        matchID_ = getDefaultInstance().getMatchID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string matchID = 1;</code>
       * @param value The bytes for matchID to set.
       * @return This builder for chaining.
       */
      public Builder setMatchIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        matchID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object team1_ = "";
      /**
       * <code>string team1 = 2;</code>
       * @return The team1.
       */
      public java.lang.String getTeam1() {
        java.lang.Object ref = team1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          team1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string team1 = 2;</code>
       * @return The bytes for team1.
       */
      public com.google.protobuf.ByteString
          getTeam1Bytes() {
        java.lang.Object ref = team1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          team1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string team1 = 2;</code>
       * @param value The team1 to set.
       * @return This builder for chaining.
       */
      public Builder setTeam1(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        team1_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string team1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeam1() {
        team1_ = getDefaultInstance().getTeam1();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string team1 = 2;</code>
       * @param value The bytes for team1 to set.
       * @return This builder for chaining.
       */
      public Builder setTeam1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        team1_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object team2_ = "";
      /**
       * <code>string team2 = 3;</code>
       * @return The team2.
       */
      public java.lang.String getTeam2() {
        java.lang.Object ref = team2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          team2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string team2 = 3;</code>
       * @return The bytes for team2.
       */
      public com.google.protobuf.ByteString
          getTeam2Bytes() {
        java.lang.Object ref = team2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          team2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string team2 = 3;</code>
       * @param value The team2 to set.
       * @return This builder for chaining.
       */
      public Builder setTeam2(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        team2_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string team2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeam2() {
        team2_ = getDefaultInstance().getTeam2();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string team2 = 3;</code>
       * @param value The bytes for team2 to set.
       * @return This builder for chaining.
       */
      public Builder setTeam2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        team2_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList comments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCommentsIsMutable() {
        if (!comments_.isModifiable()) {
          comments_ = new com.google.protobuf.LazyStringArrayList(comments_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @return A list containing the comments.
       */
      public com.google.protobuf.ProtocolStringList
          getCommentsList() {
        comments_.makeImmutable();
        return comments_;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @return The count of comments.
       */
      public int getCommentsCount() {
        return comments_.size();
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param index The index of the element to return.
       * @return The comments at the given index.
       */
      public java.lang.String getComments(int index) {
        return comments_.get(index);
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the comments at the given index.
       */
      public com.google.protobuf.ByteString
          getCommentsBytes(int index) {
        return comments_.getByteString(index);
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param index The index to set the value at.
       * @param value The comments to set.
       * @return This builder for chaining.
       */
      public Builder setComments(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommentsIsMutable();
        comments_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param value The comments to add.
       * @return This builder for chaining.
       */
      public Builder addComments(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommentsIsMutable();
        comments_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param values The comments to add.
       * @return This builder for chaining.
       */
      public Builder addAllComments(
          java.lang.Iterable<java.lang.String> values) {
        ensureCommentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, comments_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearComments() {
        comments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string comments = 4;</code>
       * @param value The bytes of the comments to add.
       * @return This builder for chaining.
       */
      public Builder addCommentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCommentsIsMutable();
        comments_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int team1Goals_ ;
      /**
       * <code>int32 team1Goals = 5;</code>
       * @return The team1Goals.
       */
      @java.lang.Override
      public int getTeam1Goals() {
        return team1Goals_;
      }
      /**
       * <code>int32 team1Goals = 5;</code>
       * @param value The team1Goals to set.
       * @return This builder for chaining.
       */
      public Builder setTeam1Goals(int value) {

        team1Goals_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 team1Goals = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeam1Goals() {
        bitField0_ = (bitField0_ & ~0x00000010);
        team1Goals_ = 0;
        onChanged();
        return this;
      }

      private int team2Goals_ ;
      /**
       * <code>int32 team2Goals = 6;</code>
       * @return The team2Goals.
       */
      @java.lang.Override
      public int getTeam2Goals() {
        return team2Goals_;
      }
      /**
       * <code>int32 team2Goals = 6;</code>
       * @param value The team2Goals to set.
       * @return This builder for chaining.
       */
      public Builder setTeam2Goals(int value) {

        team2Goals_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 team2Goals = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeam2Goals() {
        bitField0_ = (bitField0_ & ~0x00000020);
        team2Goals_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Match)
    }

    // @@protoc_insertion_point(class_scope:Match)
    private static final com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match();
    }

    public static com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Match>
        PARSER = new com.google.protobuf.AbstractParser<Match>() {
      @java.lang.Override
      public Match parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Match> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Match> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.denisbytes.javafootball.score_calculator.proto.MatchServiceProto.Match getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMatchesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMatchesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMatchesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMatchesResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Match_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Match_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEcom/github/denisbytes/javafootball/sco" +
      "re_calculator/proto/types.proto\"\023\n\021GetMa" +
      "tchesRequest\"-\n\022GetMatchesResponse\022\027\n\007ma" +
      "tches\030\001 \003(\0132\006.Match\"p\n\005Match\022\017\n\007matchID\030" +
      "\001 \001(\t\022\r\n\005team1\030\002 \001(\t\022\r\n\005team2\030\003 \001(\t\022\020\n\010c" +
      "omments\030\004 \003(\t\022\022\n\nteam1Goals\030\005 \001(\005\022\022\n\ntea" +
      "m2Goals\030\006 \001(\0052E\n\014MatchService\0225\n\nGetMatc" +
      "hes\022\022.GetMatchesRequest\032\023.GetMatchesResp" +
      "onseBN\n9com.github.denisbytes.javafootba" +
      "ll.score_calculator.protoB\021MatchServiceP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetMatchesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetMatchesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMatchesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetMatchesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetMatchesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMatchesResponse_descriptor,
        new java.lang.String[] { "Matches", });
    internal_static_Match_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Match_descriptor,
        new java.lang.String[] { "MatchID", "Team1", "Team2", "Comments", "Team1Goals", "Team2Goals", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
